Repository dxatscale/sfpowerscripts, pull requests merged in 2020-09, with the labels that each got.

#141 Display metadata during Installation of Unlocked Package
  packages/azpipelines/BuildTasks/Common/ArtifactFilePathFetcher.ts
  packages/azpipelines/BuildTasks/DeploySourceToOrgTask/DeploySourceToOrg.ts
  packages/azpipelines/BuildTasks/DeploySourceToOrgTask/task.json
  packages/azpipelines/BuildTasks/InstallUnlockedPackageTask/InstallUnlockedPackage.ts
  packages/core/src/sfdxutils/ManifestHelpers.ts
  packages/core/src/sfdxwrappers/DeploySourceToOrgImpl.ts
  packages/core/src/sfdxwrappers/InstallUnlockedPackageImpl.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/InstallUnlockedPackage.ts
Labels: enhancement

#142 Add support for reconcile profiles for source packages
  build_using_azp.ts
  package-lock.json
  package.json
  packages/azpipelines/BuildTasks/CreateSourcePackageTask/CreateSourcePackage.ts
  packages/azpipelines/BuildTasks/CreateSourcePackageTask/task.json
  packages/azpipelines/BuildTasks/InstallPackageDependenciesTask/task.json
  packages/azpipelines/BuildTasks/InstallSourcePackageTask/InstallSourcePackageToOrg.ts
  packages/azpipelines/BuildTasks/InstallSourcePackageTask/package-lock.json
  packages/azpipelines/BuildTasks/InstallSourcePackageTask/package.json
  packages/azpipelines/BuildTasks/InstallSourcePackageTask/task.json
  packages/azpipelines/BuildTasks/ManageScratchOrgTaskCurrent/ManageScratchOrg.ts
  packages/azpipelines/package-lock.json
  packages/azpipelines/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/sfdxutils/ManifestHelpers.ts
  packages/core/src/sfdxwrappers/CreateSourcePackageImpl.ts
  packages/core/src/sfdxwrappers/DeploySourceToOrgImpl.ts
  packages/core/src/sfdxwrappers/PackageMetadata.ts
  packages/core/src/sfdxwrappers/ReconcileProfileAgainstOrgImpl.ts
  packages/core/src/sfdxwrappers/index.ts
Labels: enhancement

#154 Bugfixes for generate changelog
  packages/azpipelines/BuildTasks/GenerateChangelogTask/GenerateChangelog.ts
  packages/azpipelines/BuildTasks/GenerateChangelogTask/package-lock.json
  packages/azpipelines/BuildTasks/GenerateChangelogTask/package.json
  packages/azpipelines/BuildTasks/GenerateChangelogTask/task.json
  packages/azpipelines/BuildTasks/InstallPackageDependenciesTask/package-lock.json
  packages/azpipelines/BuildTasks/InstallSourcePackageTask/task.json
  packages/azpipelines/BuildTasks/InstallUnlockedPackageTask/task.json
  packages/azpipelines/package-lock.json
  packages/azpipelines/package.json
  packages/azpipelines/vss-extension.json
  packages/sfpowerscripts-cli/package-lock.json
  packages/sfpowerscripts-cli/package.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/GenerateChangelog.ts
Labels: bug

#157 Fix Trigger Apex Test
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/parser/InterfaceFetcher.ts
  packages/core/src/parser/TestClassFetcher.ts
  packages/core/src/parser/listeners/AnnotationListener.ts
  packages/core/src/parser/listeners/InterfaceDeclarationListener.ts
  packages/core/src/parser/listeners/TestAnnotationListener.ts
  packages/core/src/sfdxwrappers/TriggerApexTestImpl.ts
Labels: Bump Required, bug, enhancement
