Repository dxatscale/sfpowerscripts, pull requests merged in 2020-12, with the labels that each got.

#243 Fix error tabulating 'null' coverage percentage for RunLocalTests
  packages/core/src/sfdxwrappers/TriggerApexTestImpl.ts
Labels: bug

#247 Deploy command
  packages/azpipelines/BuildTasks/InstallDataPackageTask/InstallDataPackage.ts
  packages/azpipelines/BuildTasks/InstallUnlockedPackageTask/InstallUnlockedPackage.ts
  packages/core/src/deploy/DeployImpl.ts
  packages/core/src/manifest/ManifestHelpers.ts
  packages/core/src/sfdxwrappers/CreateUnlockedPackageImpl.ts
  packages/core/src/sfdxwrappers/DeploySourceToOrgImpl.ts
  packages/core/src/sfdxwrappers/InstallDataPackageImpl.ts
  packages/core/src/sfdxwrappers/InstallSourcePackageImpl.ts
  packages/core/src/sfdxwrappers/InstallUnlockedPackageImpl.ts
  packages/core/src/sfdxwrappers/TriggerApexTestImpl.ts
  packages/sfpowerscripts-cli/messages/deploy.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/Build.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/Deploy.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/InstallDataPackage.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/InstallUnlockedPackage.ts
Labels: new feature

#267 Refactor Deploy Commmand to use props
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/deploy.ts
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
  packages/sfpowerscripts-cli/src/impl/prepare/PrepareASingleOrgImpl.ts
  packages/sfpowerscripts-cli/src/impl/validate/ValidateImpl.ts
Labels: enhancement

#265 Move generate changelog to 'changelog' topic
  packages/sfpowerscripts-cli/package.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/changelog/generate.ts
Labels: Major version change, breaking

#271 Align Command Names with sfdx plugin conventions
  packages/sfpowerscripts-cli/README.md
  packages/sfpowerscripts-cli/oclif.manifest.json
  packages/sfpowerscripts-cli/package-lock.json
  packages/sfpowerscripts-cli/package.json
  packages/sfpowerscripts-cli/src/BuildBase.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/analyze/pmd.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/apextests/trigger.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/apextests/validate.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/build.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/data/create.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/data/install.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/delta/create.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/incrementBuildNumber.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/source/create.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/source/install.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/unlocked/create.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/unlocked/install.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/source/deploy.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/source/deployDestructiveManifest.ts
Labels: breaking

#281 Deprecate subfolder flag for InstallSourcePackage & InstallDataPackage
  packages/azpipelines/BuildTasks/InstallDataPackageTask/InstallDataPackage.ts
  packages/azpipelines/BuildTasks/InstallDataPackageTask/task.json
  packages/azpipelines/BuildTasks/InstallSourcePackageTask/InstallSourcePackageToOrg.ts
  packages/azpipelines/BuildTasks/InstallSourcePackageTask/task.json
  packages/core/src/sfdxwrappers/InstallDataPackageImpl.ts
  packages/core/src/sfdxwrappers/InstallSourcePackageImpl.ts
  packages/sfpowerscripts-cli/messages/install_data_package.json
  packages/sfpowerscripts-cli/messages/install_source_package.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/deploy.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/data/install.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/source/install.ts
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
Labels: Major version change, breaking

#284 Refactor pre & post-deployment steps
  packages/core/src/PackageMetadata.ts
  packages/core/src/generators/SourcePackageGenerator.ts
  packages/core/src/sfdxwrappers/CreateDataPackageImpl.ts
  packages/core/src/sfdxwrappers/CreateSourcePackageImpl.ts
  packages/core/src/sfdxwrappers/CreateUnlockedPackageImpl.ts
  packages/core/src/sfdxwrappers/InstallDataPackageImpl.ts
  packages/core/src/sfdxwrappers/InstallSourcePackageImpl.ts
  packages/core/src/sfdxwrappers/InstallUnlockedPackageImpl.ts
  packages/sfpowerscripts-cli/src/InstallPackageCommand.ts
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
Labels: Major version change, breaking

#299 Update README.md
  prerequisites/scratchorgpool/README.md
Labels: documentation
