Repository dxatscale/sfpowerscripts, pull requests merged in 2020-11, with the labels that each got.

#193 Write Build result to JSON file
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/Build.ts
Labels: enhancement

#198 Add Postpack command
  packages/core/src/artifacts/ArtifactFilePathFetcher.ts
  packages/core/src/sfdxwrappers/PromoteUnlockedPackageImpl.ts
  packages/sfpowerscripts-cli/messages/postpack.json
  packages/sfpowerscripts-cli/package-lock.json
  packages/sfpowerscripts-cli/package.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/Postpack.ts
Labels: new feature

#197 Fix PromoteUnlockedPackage task
  packages/azpipelines/BuildTasks/PromoteUnlockedPackageTask/PromoteUnlockedPackage.ts
  packages/azpipelines/BuildTasks/PromoteUnlockedPackageTask/package-lock.json
  packages/azpipelines/BuildTasks/PromoteUnlockedPackageTask/package.json
  packages/azpipelines/BuildTasks/PromoteUnlockedPackageTask/task.json
Labels: bug

#199 Fix child process callback
  packages/azpipelines/BuildTasks/InstallPackageDependenciesTask/InstallPackageDependencies.ts
  packages/core/src/sfdxwrappers/AnalyzeWithPMDImpl.ts
  packages/core/src/sfdxwrappers/CreateDeltaPackageImpl.ts
  packages/core/src/sfdxwrappers/CreateScratchOrgImpl.ts
  packages/core/src/sfdxwrappers/DeployDestructiveManifestToOrgImpl.ts
  packages/core/src/sfdxwrappers/DeploySourceToOrgImpl.ts
  packages/core/src/sfdxwrappers/InstallDataPackageImpl.ts
  packages/core/src/sfdxwrappers/InstallUnlockedPackageImpl.ts
  packages/core/src/sfdxwrappers/PackageVersionListImpl.ts
  packages/core/src/sfdxwrappers/ReconcileProfileAgainstOrgImpl.ts
  packages/core/src/sfdxwrappers/TriggerApexTestImpl.ts
  packages/core/src/sfdxwrappers/ValidateDXUnlockedPackageImpl.ts
Labels: bug

#201 Move child process stderr listener outside of callback
  packages/azpipelines/BuildTasks/InstallPackageDependenciesTask/InstallPackageDependencies.ts
  packages/core/src/sfdxwrappers/CreateScratchOrgImpl.ts
  packages/core/src/sfdxwrappers/CreateUnlockedPackageImpl.ts
  packages/core/src/sfdxwrappers/InstallUnlockedPackageImpl.ts
  packages/core/src/sfdxwrappers/PackageVersionListImpl.ts
Labels: bug

#203 Fix package diff for data packages
  packages/core/src/package/PackageDiffImpl.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/CreateDataPackage.ts
Labels: bug

#205 Fix ManifestHelper getPackageType for undefined packageAliases property
  packages/core/src/manifest/ManifestHelpers.ts
Labels: bug

#204 Deprecate Export Source From Org Task
  lerna.json
  packages/azpipelines/BuildTasks/ExportSourceFromAnOrgTask/ExportSourceFromAnOrg.ts
  packages/azpipelines/BuildTasks/ExportSourceFromAnOrgTask/icon.png
  packages/azpipelines/BuildTasks/ExportSourceFromAnOrgTask/package-lock.json
  packages/azpipelines/BuildTasks/ExportSourceFromAnOrgTask/package.json
  packages/azpipelines/BuildTasks/ExportSourceFromAnOrgTask/task.json
  packages/azpipelines/BuildTasks/ExportSourceFromAnOrgTask/tsconfig.json
  packages/azpipelines/README.md
  packages/azpipelines/make.js
  packages/azpipelines/package-lock.json
  packages/azpipelines/package.json
  packages/azpipelines/vss-extension.json
Labels: Deprecated

#212 Assign permission sets as a pre-deployment step when installing data package
  packages/azpipelines/BuildTasks/InstallDataPackageTask/InstallDataPackage.ts
  packages/core/src/PackageMetadata.ts
  packages/core/src/sfdxwrappers/AssignPermissionSetsImpl.ts
  packages/core/src/sfdxwrappers/CreateDataPackageImpl.ts
  packages/core/src/sfdxwrappers/InstallDataPackageImpl.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/InstallDataPackage.ts
Labels: enhancement

#213 Fix Package Diff for Data packages
  packages/azpipelines/BuildTasks/CreateDataPackageTask/CreateDataPackage.ts
  packages/core/src/package/PackageDiffImpl.ts
  packages/core/src/sfdxwrappers/CreateDataPackageImpl.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/CreateDataPackage.ts
Labels: bug

#214 Fix bug in postpack command
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/Postpack.ts
Labels: bug

#216 Hide unchanged artifacts from changelong markdown
  packages/azpipelines/BuildTasks/GenerateChangelogTask/GenerateChangelog.ts
  packages/azpipelines/BuildTasks/GenerateChangelogTask/task.json
  packages/core/src/changelog/GenerateChangelogMarkdown.ts
  packages/sfpowerscripts-cli/messages/generate_changelog.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/GenerateChangelog.ts
Labels: enhancement

#219 Fix TriggerApexTest task
  packages/core/src/sfdxwrappers/TriggerApexTestImpl.ts
Labels: bug

#222 Reformat changelog markdown
  packages/core/src/changelog/GenerateChangelogMarkdown.ts
Labels: enhancement

#226 Deprecate Export Source command in CLI
  packages/azpipelines/package-lock.json
  packages/azpipelines/package.json
  packages/azpipelines_release_management_extensions/package-lock.json
  packages/azpipelines_release_management_extensions/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/sfdxwrappers/ExportSourceFromAnOrgImpl.ts
  packages/core/src/utils/Extract.ts
  packages/sfpowerscripts-cli/README.md
  packages/sfpowerscripts-cli/messages/export_source.json
  packages/sfpowerscripts-cli/src/SfpowerscriptsCommand.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/ExportSource.ts
Labels: Deprecated

#224 Refactor artifact structure for single zip artifact
  packages/azpipelines/BuildTasks/CreateDataPackageTask/CreateDataPackage.ts
  packages/azpipelines/BuildTasks/CreateDataPackageTask/task.json
  packages/azpipelines/BuildTasks/CreateDeltaPackageTask/CreateDeltaPackage.ts
  packages/azpipelines/BuildTasks/CreateSourcePackageTask/CreateSourcePackage.ts
  packages/azpipelines/BuildTasks/CreateSourcePackageTask/task.json
  packages/azpipelines/BuildTasks/CreateUnlockedPackageTask/CreateUnlockedPackage.ts
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/artifacts/ArtifactFilePathFetcher.ts
  packages/core/src/generators/ArtifactGenerator.ts
  packages/sfpowerscripts-cli/messages/install_package_command.json
  packages/sfpowerscripts-cli/src/InstallPackageCommand.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/Build.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/CreateDataPackage.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/CreateDeltaPackage.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/CreateSourcePackage.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/CreateUnlockedPackage.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/InstallDataPackage.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/InstallSourcePackage.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/InstallUnlockedPackage.ts
Labels: enhancement

#225 Promote command
  packages/sfpowerscripts-cli/messages/postpack.json
  packages/sfpowerscripts-cli/messages/promote.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/Postpack.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/Promote.ts
Labels: new feature

#230 Apply quick fix for handling zip artifacts in CLI InstallPackageCommand
  packages/sfpowerscripts-cli/src/InstallPackageCommand.ts
Labels: bug

#237 Refactor artifactFilePathFetcher
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/artifacts/ArtifactFilePathFetcher.ts
  packages/core/src/generators/ArtifactGenerator.ts
  packages/sfpowerscripts-cli/src/InstallPackageCommand.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/InstallDataPackage.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/InstallSourcePackage.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/InstallUnlockedPackage.ts
Labels: enhancement

#238 Publish command
  packages/core/src/artifacts/ArtifactFilePathFetcher.ts
  packages/sfpowerscripts-cli/messages/publish.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/Publish.ts
Labels: new feature
