Repository dxatscale/sfpowerscripts, pull requests merged in 2021-03, with the labels that each got.

#406 Update README.md
  README.md
Labels: documentation

#409 Impact analysis on Validate
  packages/core/package.json
  packages/core/resources/metadatainfo.json
  packages/core/src/metadata/metadataFiles.ts
  packages/core/src/metadata/metadataInfo.ts
  packages/core/src/utils/fileutils.ts
  packages/sfpowerscripts-cli/messages/validate.json
  packages/sfpowerscripts-cli/package-lock.json
  packages/sfpowerscripts-cli/package.json
  packages/sfpowerscripts-cli/resources/cytoscape-dagre.js
  packages/sfpowerscripts-cli/resources/cytoscape.min.js
  packages/sfpowerscripts-cli/resources/dagre.js
  packages/sfpowerscripts-cli/resources/markup.hbs
  packages/sfpowerscripts-cli/resources/script.hbs
  packages/sfpowerscripts-cli/resources/styles.css
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/validate.ts
  packages/sfpowerscripts-cli/src/impl/validate/DependencyAnalysis.ts
  packages/sfpowerscripts-cli/src/impl/validate/ValidateImpl.ts
Labels: new feature, temporary

#411 Show text exec error instead of missing test report error
  packages/core/src/sfpcommands/apextest/TriggerApexTests.ts
Labels: bug

#414 Deploy latest artifact version
  packages/sfpowerscripts-cli/package-lock.json
  packages/sfpowerscripts-cli/package.json
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
Labels: enhancement

#416 Fail when apext tests are not available
  packages/core/src/sfdxwrappers/TriggerApexTestImpl.ts
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
Labels: bug

#424 Use artifactFilePathFetcher in changelog:generate command
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/changelog/generate.ts
Labels: bug

#423 Publish artifacts to a NPM registry
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/artifacts/ArtifactFilePathFetcher.ts
  packages/core/tests/artifacts/ArtifactsFromFileSystem.test.ts
  packages/sfpowerscripts-cli/README.md
  packages/sfpowerscripts-cli/messages/prepare.json
  packages/sfpowerscripts-cli/messages/publish.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/prepare.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/publish.ts
  packages/sfpowerscripts-cli/src/impl/prepare/PrepareImpl.ts
Labels: enhancement

#437 Only check if packages are installed at the start of Deploy, and not in each individual package installation
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
Labels: bug

#438 All package types must be promoted to be deployed to production
  packages/core/src/PackageMetadata.ts
  packages/core/src/org/OrgDetails.ts
  packages/sfpowerscripts-cli/messages/deploy.json
  packages/sfpowerscripts-cli/messages/promote.json
  packages/sfpowerscripts-cli/package-lock.json
  packages/sfpowerscripts-cli/package.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/deploy.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/promote.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/publish.ts
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
Labels: breaking

#441 Remove usage of npx to trigger sfdx commands
  packages/core/src/sfdxwrappers/AnalyzeWithPMDImpl.ts
  packages/core/src/sfdxwrappers/DeleteScratchOrgImpl.ts
  packages/core/src/sfdxwrappers/DeployDestructiveManifestToOrgImpl.ts
  packages/core/src/sfdxwrappers/PromoteUnlockedPackageImpl.ts
  packages/core/src/sfdxwrappers/ReconcileProfileAgainstOrgImpl.ts
  packages/core/src/sfdxwrappers/ValidateDXUnlockedPackageImpl.ts
  packages/core/src/sfdxwrappers/ValidateTestCoveragePackageImpl.ts
  packages/core/src/sfpcommands/package/CreateUnlockedPackageImpl.ts
Labels: internal

#439 Display Error during package list
  packages/core/src/sfdxwrappers/PackageVersionListImpl.ts
  packages/core/src/sfpcommands/package/CreateUnlockedPackageImpl.ts
Labels: bug

#446 Close chromium before returning control to ValidateImpl
  packages/sfpowerscripts-cli/src/impl/validate/DependencyAnalysis.ts
Labels: bug

#447 Change implementation for required scope
  packages/sfpowerscripts-cli/messages/prepare.json
  packages/sfpowerscripts-cli/messages/publish.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/prepare.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/publish.ts
Labels: bug

#449 Fix deployment of scoped artifacts
  packages/core/src/artifacts/ArtifactFilePathFetcher.ts
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
Labels: bug

#448 Validate flags on command initialisation
  packages/sfpowerscripts-cli/src/SfpowerscriptsCommand.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/prepare.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/publish.ts
Labels: wip

#456 Fix filter for deployment queue
  packages/sfpowerscripts-cli/package-lock.json
  packages/sfpowerscripts-cli/package.json
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
Labels: bug

#460 Add architectural design records for release command
  ADR/release/release-1-0.md
  ADR/release/release-1-1.md
Labels: documentation

#469 Fix OrgCoverage Packages should not be tested for coverage check
  packages/core/src/sfpcommands/package/CreateUnlockedPackageImpl.ts
Labels: bug, hotfix
