Repository dxatscale/sfpowerscripts, pull requests merged in 2021-05, with the labels that each got.

#515 Fix order in which releases are searched for latest commit Id
  packages/sfpowerscripts-cli/src/impl/changelog/ReleaseChangelogUpdater.ts
Labels: bug

#516 Fix OrgsUpdater identifying new releases as old
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/changelog/generate.ts
  packages/sfpowerscripts-cli/src/impl/changelog/OrgsUpdater.ts
  packages/sfpowerscripts-cli/src/impl/changelog/ReleaseChangelogUpdater.ts
  packages/sfpowerscripts-cli/tests/impl/changelog/OrgUpdater.test.ts
Labels: bug

#518 Fix merge conflict when multiple instances are pushing changelog
  packages/sfpowerscripts-cli/src/impl/changelog/ChangelogImpl.ts
Labels: bug

#525 Show name and context on package validation fail
  packages/sfpowerscripts-cli/src/ProjectValidation.ts
  packages/sfpowerscripts-cli/tests/ProjectValidation.test.ts
Labels: enhancement

#529 Remove automated branch generation for changelogs
  .gitignore
  packages/sfpowerscripts-cli/messages/release.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/changelog/generate.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/release.ts
  packages/sfpowerscripts-cli/src/impl/changelog/ChangelogImpl.ts
  packages/sfpowerscripts-cli/src/impl/release/ReleaseImpl.ts
Labels: Major version change, breaking, bug

#500 Creating release branches
  decision records/release/005-cutting-release-branch.md
Labels: decison, proposal

#499 Artifact version duplication
  decision records/artifacts/001-artifact-version-duplication.md
Labels: decison, proposal
