Repository dxatscale/sfpowerscripts, pull requests merged in 2021-02, with the labels that each got.

#355 Update CLI README.md
  packages/sfpowerscripts-cli/README.md
Labels: documentation

#358 Allow packageDiffImpl to work with merge commits
  azure-pipelines.yml
  packages/core/src/package/PackageDiffImpl.ts
  packages/core/src/utils/Git.ts
  packages/core/src/utils/GitTags.ts
  packages/core/tests/package/PackageDiffImpl.test.ts
  packages/core/tests/utils/GitTags.test.ts
Labels: enhancement

#359 Update prepare command README
  packages/sfpowerscripts-cli/README.md
  packages/sfpowerscripts-cli/messages/prepare.json
Labels: documentation

#360 Package Build Collections
  build_templates/buildcli.yml
  packages/sfpowerscripts-cli/jest.config.js
  packages/sfpowerscripts-cli/package-lock.json
  packages/sfpowerscripts-cli/package.json
  packages/sfpowerscripts-cli/src/impl/parallelBuilder/BuildCollections.ts
  packages/sfpowerscripts-cli/src/impl/parallelBuilder/BuildImpl.ts
  packages/sfpowerscripts-cli/src/impl/parallelBuilder/UndirectedGraph.ts
  packages/sfpowerscripts-cli/src/impl/pool/sfdxnode/buildArgs.ts
  packages/sfpowerscripts-cli/tests/impl/parallelBuilder/BuildCollections.test.ts
  packages/sfpowerscripts-cli/tests/impl/parallelBuilder/UndirectedGraph.test.ts
  packages/sfpowerscripts-cli/tsconfig.json
Labels: new feature

#369 Fix bug in GitTags when the package does not have any tags
  packages/core/src/utils/GitTags.ts
  packages/core/tests/utils/GitTags.test.ts
Labels: bug

#371 Use stage forceignore file in PackageDiffImpl
  packages/core/src/package/PackageDiffImpl.ts
  packages/sfpowerscripts-cli/src/impl/parallelBuilder/BuildImpl.ts
Labels: bug

#372 Fix issue with displaying test results on failure
  packages/core/src/sfpcommands/apextest/TriggerApexTests.ts
Labels: bug

#377 Fix Regression on missing statsD for TriggerApexTest
  packages/core/src/sfpcommands/apextest/TriggerApexTests.ts
Labels: bug

#383 Fix DeployImpl
  packages/core/src/artifacts/ArtifactFilePathFetcher.ts
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
  packages/sfpowerscripts-cli/src/impl/parallelBuilder/BuildImpl.ts
Labels: bug

#388 Show test execution error message
  packages/core/src/sfpcommands/apextest/TriggerApexTests.ts
Labels: bug

#395 Fix Deploy StatsD Metrics
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/deploy.ts
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
Labels: bug

#400 Fix Logs to display errors if artifacts are not found in the org
  packages/core/src/artifacts/ArtifactInstallationStatusChecker.ts
  packages/core/src/artifacts/InstalledAritfactsFetcher.ts
Labels: bug
