Repository dxatscale/sfpowerscripts, pull requests merged in 2021-06, with the labels that each got.

#493 Create 004-Identifying-packages-in-npm.md
  decision records/release/004-Identifying-packages-in-npm.md
Labels: decison, proposal

#560 Include untouched Apex classes & triggers in package coverage calculation
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/package/PackageTestCoverage.ts
  packages/core/src/sfpcommands/apextest/TriggerApexTests.ts
  packages/core/tests/package/PackageTestCoverage.test.ts
Labels: bug

#548 Update docs with new Sfpowerscripts Artifact package version ID
  packages/sfpowerscripts-cli/README.md
  prerequisites/sfpowerscripts-artifact/README.md
Labels: documentation
