Repository dxatscale/sfpowerscripts, pull requests merged in 2021-08, with the labels that each got.

#644 Fix Broken PMD Analysis
  packages/core/src/sfpowerkitwrappers/AnalyzeWithPMDImpl.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/analyze/pmd.ts
Labels: hotfix

#652 Add sample how to pass build number to build command
  faq/package-types/source-packages.md
Labels: documentation

#648 Add Header to fetch command
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/pool/fetch.ts
Labels: enhancement

#641 Documentation/dr dependency manager
  decision records/003-Depenedency-Manager.md
Labels: proposal

#655 Fix logging for package:<type>:create commands
  packages/core/src/sfpcommands/package/CreateDataPackageImpl.ts
  packages/core/src/sfpcommands/package/CreateSourcePackageImpl.ts
  packages/core/src/sfpcommands/package/CreateUnlockedPackageImpl.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/data/create.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/source/create.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/unlocked/create.ts
Labels: bug, hotfix

#660 Fix misusage of test results from previous runs
  packages/core/src/sfpcommands/apextest/TriggerApexTests.ts
Labels: bug, hotfix

#657 Align packages metrics across orchestrator commands
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/deploy.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/prepare.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/release.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/validate.ts
  packages/sfpowerscripts-cli/src/errors/ValidateError.ts
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
  packages/sfpowerscripts-cli/src/impl/pool/PoolCreateImpl.ts
  packages/sfpowerscripts-cli/src/impl/prepare/PrepareOrgJob.ts
  packages/sfpowerscripts-cli/src/impl/validate/ValidateImpl.ts
Labels: bug

#661 Publish number of work items and commits in a release as metrics
  packages/sfpowerscripts-cli/src/impl/changelog/ChangelogImpl.ts
  packages/sfpowerscripts-cli/src/impl/release/ReleaseImpl.ts
Labels: enhancement

#671 Require --branchname parameter when generating a release changelog
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/release.ts
Labels: bug
