Repository dxatscale/sfpowerscripts, pull requests merged in 2021-07, with the labels that each got.

#578 Update docs for prepare command
  packages/sfpowerscripts-cli/README.md
  packages/sfpowerscripts-cli/messages/prepare.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/prepare.ts
Labels: documentation

#579 Skip data packages when creating source tracking resources
  packages/sfpowerscripts-cli/src/impl/pool/SourceTrackingResourceController.ts
Labels: bug

#588 Remove dependency on deprecated module request-promise-native
  packages/sfpowerscripts-cli/src/impl/pool/services/fetchers/ScratchOrgInfoFetcher.ts
Labels: bug

#592 Fix default deployment mode
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/prepare.ts
  packages/sfpowerscripts-cli/src/impl/prepare/PrepareOrgJob.ts
Labels: bug

#595 Fix Blank Error Message during a deployment failure
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
Labels: bug

#598 Push source using force parameter
  packages/core/src/sfdxwrappers/PushSourceImpl.ts
Labels: bug

#600 Fix test class identification
  packages/core/src/parser/listeners/ApexTypeListener.ts
Labels: bug

#608 Cleanup prerequisites
  prerequisites/scratchorgpool/.gitignore
  prerequisites/scratchorgpool/README.md
  prerequisites/scratchorgpool/config/project-scratch-def.json
  prerequisites/scratchorgpool/scratchorg-poolconfig.json
  prerequisites/scratchorgpool/sfdx-project.json
  prerequisites/sfpowerscripts-artifact/package.json
Labels: documentation

#621 Check for existence of configuration files
  packages/core/src/sfpcommands/package/CreateDataPackageImpl.ts
Labels: enhancement

#628 Fix working directory for SfdmuRunImpl
  packages/core/src/sfpcommands/package/InstallDataPackageImpl.ts
Labels: bug

#630 Convert alias to username in OrgDetailsFetcher
  packages/core/src/org/OrgDetailsFetcher.ts
Labels: bug

#631 Fix OrgDetailsFetcher
  packages/core/src/org/OrgDetailsFetcher.ts
Labels: bug
