Repository dxatscale/sfpowerscripts, pull requests merged in 2021-04, with the labels that each got.

#472 Add isApexFound and isProfilesFound to unlocked package metadata
  packages/core/src/sfpcommands/package/CreateUnlockedPackageImpl.ts
Labels: bug

#481 Fix InstalledArtifactsFetcher for use case with multiple orgs
  packages/core/src/artifacts/InstalledAritfactsFetcher.ts
  packages/core/tests/artifacts/ArtifactsToOrg.test.ts
Labels: bug, hotfix

#486 Add a reporting table for build
  .github/workflows/review.yml
  packages/core/package.json
  packages/core/src/package/PackageDiffImpl.ts
  packages/core/tests/package/PackageDiffImpl.test.ts
  packages/sfpowerscripts-cli/package.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/data/create.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/source/create.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/unlocked/create.ts
  packages/sfpowerscripts-cli/src/impl/parallelBuilder/BuildImpl.ts
Labels: enhancement

#509 Add support for checkpoints in prepare
  packages/sfpowerscripts-cli/resources/schemas/sfdx-project.schema.json
  packages/sfpowerscripts-cli/src/impl/pool/utils/ScratchOrgUtils.ts
  packages/sfpowerscripts-cli/src/impl/prepare/PrepareASingleOrgImpl.ts
  packages/sfpowerscripts-cli/src/impl/prepare/PrepareImpl.ts
Labels: enhancement
