Repository dxatscale/sfpowerscripts, pull requests merged in 2021-11, with the labels that each got.

#748 Fix profile redeployment for source package installations
  packages/core/src/package/PackageManifest.ts
  packages/core/src/package/SFPPackage.ts
  packages/core/src/package/packageInstallers/InstallSourcePackageImpl.ts
  packages/core/tests/package/SFPackage.test.ts
Labels: bug

#746 Refactor Create Package
  packages/core/src/apex/parser/ApexTypeFetcher.ts
  packages/core/src/package/coverage/PackageVersionCoverage.ts
  packages/core/src/package/packageCreators/CreateDataPackageImpl.ts
  packages/core/src/package/packageCreators/CreatePackage.ts
  packages/core/src/package/packageCreators/CreateSourcePackageImpl.ts
  packages/core/src/package/packageCreators/CreateUnlockedPackageImpl.ts
  packages/core/src/sfdxwrappers/ConvertSourceToMDAPIImpl.ts
  packages/core/src/sfdxwrappers/CreateUnlockedPackageVersionImpl.ts
  packages/core/src/sfpcommands/package/CreateDataPackageImpl.ts
  packages/core/src/sfpcommands/package/CreateSourcePackageImpl.ts
  packages/core/src/sfpcommands/package/CreateUnlockedPackageImpl.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/data/create.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/source/create.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/package/unlocked/create.ts
  packages/sfpowerscripts-cli/src/impl/parallelBuilder/BuildImpl.ts
Labels: refactor

#750 fix(metrics): Wrong reporting of apex test metrics
  packages/core/src/sfpcommands/apextest/TriggerApexTests.ts
Labels: bug

#752 Fix deployment of default directory for aliasfied packages
  packages/core/src/package/packageInstallers/InstallPackage.ts
Labels: bug

#755 Enable pools to succeed on deployment errors by default
  packages/sfpowerscripts-cli/resources/schemas/pooldefinition.schema.json
  packages/sfpowerscripts-cli/src/impl/prepare/PrepareImpl.ts
Labels: enhancement, breaking

#763 feat(package manfiest)!: create package manifest from scratch
  packages/core/src/package/PackageManifest.ts
  packages/core/src/package/SFPPackage.ts
  packages/core/src/sfpcommands/source/DeploySourceToOrgImpl.ts
  packages/core/src/sfpcommands/source/PushSourceToOrgImpl.ts
  packages/core/tests/package/PackageManifest.test.ts
Labels: breaking

#766 fix(cli-table): set cli-table dependency to version 0.3.6
  packages/core/package-lock.json
  packages/core/package.json
  packages/sfpowerscripts-cli/package-lock.json
  packages/sfpowerscripts-cli/package.json
Labels: bug

#769 fix(forceignore): create Packages not using the proper forceignore files
  packages/core/src/package/packageCreators/CreatePackage.ts
Labels: hotfix

#771 Validate dependencies as part of orchestrator:validate command
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/dependency/ChangedComponentsFetcher.ts
  packages/core/src/dependency/Component.ts
  packages/core/src/dependency/DependencyAnalysis.ts
  packages/core/src/dependency/DependencyFetcher.ts
  packages/core/src/dependency/DependencyViolation.ts
  packages/core/src/dependency/Entrypoint.ts
  packages/core/src/display/DependencyViolationDisplayer.ts
  packages/core/src/sfpcommands/source/DeploySourceToOrgImpl.ts
  packages/sfpowerscripts-cli/messages/validate.json
  packages/sfpowerscripts-cli/package-lock.json
  packages/sfpowerscripts-cli/package.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/validate.ts
  packages/sfpowerscripts-cli/src/errors/ValidateError.ts
  packages/sfpowerscripts-cli/src/impl/validate/ImpactAnalysis.ts
  packages/sfpowerscripts-cli/src/impl/validate/ValidateImpl.ts
  packages/sfpowerscripts-cli/src/impl/validate/ValidateResult.ts
Labels: enhancement
