Repository dxatscale/sfpowerscripts, pull requests merged in 2022-08, with the labels that each got.

#1085 Downgrade sfdx data plugin to 2.0.0
  dockerfiles/sfpowerscripts.Dockerfile
Labels: hotfix

#1087 Issue/1086
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/releasedefinition/generate.ts
Labels: bug

#1091 feat(releasedefn): generate release defintion based on a yaml configuration
  packages/sfpowerscripts-cli/messages/releasedefinition_generate.json
  packages/sfpowerscripts-cli/resources/schemas/releasedefinitiongenerator.schema.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/releasedefinition/generate.ts
  packages/sfpowerscripts-cli/src/impl/release/ReleaseDefinitionGenerator.ts
  packages/sfpowerscripts-cli/src/impl/release/ReleaseDefinitionGeneratorConfigSchema.ts
Labels: breaking

#1106 Decision Record: Automated generation of release definitions
  decision records/release/006-release-defn-generator.md
Labels: decison
