Repository dxatscale/sfpowerscripts, pull requests merged in 2022-03, with the labels that each got.

#873 feat(shell-executor): add an environment variable SPFOWERSCRIPTS_DEFAULT_SHELL to select shell
  packages/core/src/package/packageInstallers/PackageInstallationHelpers.ts
  packages/core/src/utils/DefaultShell.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/publish.ts
  packages/sfpowerscripts-cli/src/impl/artifacts/FetchAnArtifactUsingScript.ts
Labels: enhancement

#865 refactor/artifacts
  packages/core/package-lock.json
  packages/core/src/artifacts/ArtifactFilePathFetcher.ts
  packages/core/src/artifacts/ArtifactInstallationStatusChecker.ts
  packages/core/src/artifacts/ArtifactInstallationStatusUpdater.ts
  packages/core/src/artifacts/ArtifactMigrator.ts
  packages/core/src/artifacts/InstalledAritfactsFetcher.ts
  packages/core/src/dependency/DependencyAnalysis.ts
  packages/core/src/org/SFPOrg.ts
  packages/core/src/org/packageQuery/InstalledPackagesQueryExecutor.ts
  packages/core/src/package/packageCreators/CreateUnlockedPackageImpl.ts
  packages/core/src/package/packageInstallers/InstallPackage.ts
  packages/core/src/package/packageInstallers/InstallUnlockedPackageImpl.ts
  packages/core/src/package/packageQuery/InstalledPackagesFetcher.ts
  packages/core/src/package/packageQuery/PackageFetcher.ts
  packages/core/src/utils/ObjectCRUDHelper.ts
  packages/core/tests/artifacts/ArtifactsToOrg.test.ts
  packages/core/tests/org/ArtifactsToOrg.test.ts
  packages/core/tests/org/ListAllPackages.test.ts
  packages/sfp-cli/package-lock.json
  packages/sfp-cli/src/workflows/org/CreateAnOrgWorkflow.ts
  packages/sfpowerscripts-cli/package-lock.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/pool/fetch.ts
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
  packages/sfpowerscripts-cli/src/impl/release/ReleaseImpl.ts
  packages/sfpowerscripts-cli/src/impl/validate/ValidateImpl.ts
Labels: breaking, refactor

#876 refactor/apex tests
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/apextest/ClearCodeCoverage.ts
  packages/core/src/apextest/ExtendedTestOptions.ts
  packages/core/src/apextest/JSONReporter.ts
  packages/core/src/apextest/TestOptions.ts
  packages/core/src/apextest/TestReportDisplayer.ts
  packages/core/src/apextest/TriggerApexTests.ts
  packages/core/src/sfdxwrappers/TriggerApexTestImpl.ts
  packages/core/src/sfpcommands/apextest/TriggerApexTests.ts
  packages/core/src/sfpowerkitwrappers/ValidateTestCoveragePackageImpl.ts
  packages/core/tests/sfdxwrappers/TriggerApexTestImpl.test.ts
  packages/core/tests/sfpcommands/TriggerApexTestApexTestInPackage.test.ts
  packages/core/tests/sfpcommands/TriggerApexTestSpecifiedTests.test.ts
  packages/sfp-cli/src/impl/sfpcommands/TriggerApexTest.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/apextests/trigger.ts
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
Labels: breaking, refactor

#883 refactor(deploy-source): refactor DeploySource to use SDR
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/apextest/ApexTestSuite.ts
  packages/core/src/display/DeployErrorDisplayer.ts
  packages/core/src/display/PackageComponentPrinter.ts
  packages/core/src/sfpcommands/source/DeploySourceToOrgImpl.ts
  packages/core/tests/apextest/ApexTestSuite.test.ts
Labels: refactor

#866 docs(decision record): implementation of source tracking on prepare command
  decision records/prepare/001-prepare-source-tracking.md
Labels: decison

#837 Migrate CI/CD from Azure Pipelines to Github Actions
  .github/workflows/buildPackages.yml
  .github/workflows/promotePackage.yml
  .github/workflows/release.yml
  azure-pipelines.yml
  build_templates/buildcli.yml
  build_templates/promotePackage.yml
Labels: CI/CD

#911 Add diffcheck flag to validate commands
  packages/core/src/apextest/TriggerApexTests.ts
  packages/core/src/package/packageInstallers/InstallPackage.ts
  packages/sfpowerscripts-cli/messages/validate.json
  packages/sfpowerscripts-cli/messages/validateAgainstOrg.json
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/validate.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/validateAgainstOrg.ts
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
  packages/sfpowerscripts-cli/src/impl/validate/ValidateImpl.ts
Labels: enhancement
