Repository dxatscale/sfpowerscripts, pull requests merged in 2022-04, with the labels that each got.

#920 doc(dr): DR for migration to salesforce libs
  decision records/004-cli-to-libs.md
Labels: documentation

#922 fix(build): Throw error in build when remote origin is not set
  packages/sfpowerscripts-cli/src/impl/parallelBuilder/BuildImpl.ts
Labels: bug

#923 docs(dr): add a dr on automated retry of apex tests
  decision records/validate/001-automated-apex-testing-retry.md
Labels: documentation

#921 fix(schema): Remove unsupported entities
  packages/sfpowerscripts-cli/resources/schemas/sfdx-project.schema.json
Labels: bug

#929 fix(sfp-org): fetch artitfacts installed in the order of committed
  packages/core/src/org/SFPOrg.ts
  packages/core/src/scratchorg/pool/ClientSourceTracking.ts
Labels: bug

#945 feat(fast-feedback): experimental mode for faster feedback during validate
  packages/core/src/apexLinkWrapper/ApexLinkCheckImpl.ts
  packages/core/src/apextest/ImpactedApexTestClassFetcher.ts
  packages/core/src/apextest/TriggerApexTests.ts
  packages/sfpowerscripts-cli/src/commands/sfpowerscripts/orchestrator/validate.ts
  packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts
  packages/sfpowerscripts-cli/src/impl/validate/ValidateImpl.ts
Labels: experimental

#954 fix(scripts): fix paths to pre and post deployment scripts when executed without repository
  packages/core/src/package/generators/SourcePackageGenerator.ts
Labels: bug
