Repository dxatscale/sfpowerscripts, pull requests merged in 2023-10, with the labels that each got.

#1420 feat(install): introduce a unified package installation command
  packages/sfpowerscripts-cli/messages/install_data_package.json
  packages/sfpowerscripts-cli/messages/install_package.json
  packages/sfpowerscripts-cli/messages/install_source_package.json
  packages/sfpowerscripts-cli/messages/install_unlocked_package.json
  packages/sfpowerscripts-cli/src/InstallPackageCommand.ts
  packages/sfpowerscripts-cli/src/commands/package/data/install.ts
  packages/sfpowerscripts-cli/src/commands/package/install.ts
  packages/sfpowerscripts-cli/src/commands/package/source/install.ts
  packages/sfpowerscripts-cli/src/commands/package/unlocked/install.ts
Labels: medium, waiting-for-review

#1421 feat: use node 18 LTS instead of the latest 20.x version
  dockerfiles/sfpowerscripts.Dockerfile
Labels: small, waiting-for-review

#1423 fix(packagediff): fix packages being built when the path to package start with same structure
  packages/core/src/package/diff/PackageDiffImpl.ts
  packages/core/tests/package/PackageDiffImpl.test.ts
Labels: small, waiting-for-review

#1424 fix(README): contributors link target dx@scale repo
  README.md
Labels: small, waiting-for-review, docs

#1429 fix(WorkItemFilters): Support multiple workItem filters
  packages/sfpowerscripts-cli/src/impl/release/ReleaseImpl.ts
  packages/sfpowerscripts-cli/tests/impl/changelog/WorkItemUpdater.test.ts
Labels: small, waiting-for-review

#1432 display login URL instead of instance URL for scratch orgs
  packages/sfpowerscripts-cli/src/ui/OrgInfoDisplayer.ts
Labels: small, waiting-for-review

#1431 1430: Update example commands and typos
  packages/sfpowerscripts-cli/messages/releasedefinition_generate.json
  packages/sfpowerscripts-cli/src/commands/releasedefinition/generate.ts
Labels: documentation, small, waiting-for-review
