Repository dxatscale/sfpowerscripts, pull requests merged in 2023-06, with the labels that each got.

#1324 docs: dr on migration to standalone cli
  decision records/009-Migrating from 
Labels: documentation, decision, small, waiting-for-review

#1325 docs: add a dr on ship-show-ask model used bysfpowercripts
  decision records/010-ship-show-ask-model.md
Labels: small, waiting-for-review, docs

#1292 feat: add support for picklist deployment
  .gitignore
  packages/core/src/package/SfpPackage.ts
  packages/core/src/package/analyser/AnalyzerRegistry.ts
  packages/core/src/package/analyser/PicklistAnalyzer.ts
  packages/core/src/package/deploymentCustomizers/DeploymentCustomizer.ts
  packages/core/src/package/deploymentCustomizers/FHTEnabler.ts
  packages/core/src/package/deploymentCustomizers/FTEnabler.ts
  packages/core/src/package/deploymentCustomizers/MetadataDeploymentCustomizer.ts
  packages/core/src/package/deploymentCustomizers/PicklistEnabler.ts
  packages/core/src/package/deploymentCustomizers/PostDeployersRegistry.ts
  packages/core/src/package/deploymentCustomizers/PreDeployersRegistry.ts
  packages/core/src/package/packageInstallers/InstallPackage.ts
  packages/core/src/package/postDeployers/PostDeployer.ts
  packages/sfpowerscripts-cli/resources/schemas/sfdx-project.schema.json
Labels: large, waiting-for-review

#1334 Increment browserforce plugin to v2.11.0
  dockerfiles/sfpowerscripts.Dockerfile
Labels: small, waiting-for-review

#1322 support branched package dependency
  packages/core/src/package/dependencies/PackageDependencyResolver.ts
  packages/core/src/package/version/Package2VersionFetcher.ts
  packages/core/tests/package/Package2VersionFetcher.test.ts
  packages/core/tests/package/dependencies/PackageDependencyResolver.test.ts
  packages/sfpowerscripts-cli/resources/schemas/sfdx-project.schema.json
  packages/sfpowerscripts-cli/src/impl/parallelBuilder/BuildImpl.ts
Labels: large, waiting-for-review

#1336 fix(picklist): fix org response and exclude custom metadata picklists
  packages/core/src/package/deploymentCustomizers/PicklistEnabler.ts
Labels: small, waiting-for-review

#1337 fix(browserforce): revert "Increment browserforce plugin to v2.11.0"
  dockerfiles/sfpowerscripts.Dockerfile
Labels: small, waiting-for-review
