Repository dxatscale/sfpowerscripts, pull requests merged in 2023-09, with the labels that each got.

#1400 fix(schema): update schema to remove warning around seedMetadata
  packages/sfpowerscripts-cli/resources/schemas/sfdx-project.schema.json
Labels: medium, waiting-for-review

#1370 fix(package): install using v58.0 PackageInstallRequest parameters
  packages/sfpowerscripts-cli/src/commands/package/unlocked/install.ts
Labels: small, waiting-for-review

#1401 Arrange badges and deprecate broken one :)
  README.md
Labels: small, waiting-for-review, docs

#1409 Bugfix/use lower uid in dockerfiles
  dockerfiles/sfpowerscripts.Dockerfile
Labels: medium, waiting-for-review

#1404 fix: enable json flag for pool fetch command
  packages/sfpowerscripts-cli/src/commands/pool/fetch.ts
Labels: small, waiting-for-review

#1353 feat: profile merge and retrieve
  packages/sfpowerscripts-cli/messages/profile_retrieve.json
  packages/sfpowerscripts-cli/src/SfpowerscriptsCommand.ts
  packages/sfpowerscripts-cli/src/commands/profile/merge.ts
  packages/sfpowerscripts-cli/src/commands/profile/reconcile.ts
  packages/sfpowerscripts-cli/src/commands/profile/retrieve.ts
Labels: large, waiting-for-review
